/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbank;

import javax.swing.JOptionPane;

/**
 *
 * @author MS
 */
public class pilih extends javax.swing.JFrame {

    /**
     * Creates new form pilih
     */
    public pilih() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tbpilih = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PILIH TRANSAKSI");

        jLabel2.setText("[1] INFORMASI SALDO");

        jLabel3.setText("[2] PENYETORAN");

        jLabel4.setText("[3] PENARIKAN");

        jLabel5.setText("[4] PETUNJUK");

        jLabel6.setText("[5] KELUAR");

        tbpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbpilihActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Masukkan pilihan Anda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(141, 141, 141))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(tbpilih, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbpilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbpilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpilihActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String str, setor;
        int str1, tab=50000, setor1, tab1 ;
        str = tbpilih.getText();
        str1 = Integer.parseInt(str);

        switch(str1)
        {
            //kode pengecekan saldo
            case 1:
            if(tbpilih.getText().equals(""))
            {JOptionPane.showMessageDialog(null,"Silakan isi PIN anda","ERROR",1);}
            JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : " + tab);
            tbpilih.setText("");
            break;

            //kode penyetoran
            case 2:
            //dialog input
            if(tbpilih.getText().equals(""))
            {JOptionPane.showMessageDialog(null,"Silakan isi PIN anda","ERROR",1);}
            setor = JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran: " );
            setor1 = Integer.parseInt(setor);
            //jika kosong
            if(setor1<50000){
                JOptionPane.showMessageDialog(null,"Minimal penyetoran adalah Rp50.000");
                tbpilih.setText("");
            }
            //jika berhasil
            else{tab1 = tab+setor1;
                JOptionPane.showMessageDialog(null,"Penyetoran berhasil. \n Saldo anda adalah Rp."+tab1 );
                tbpilih.setText("");}
            break;

            //kode penarikan
            case 3:
            setor = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan: " );
            setor1 = Integer.parseInt(setor);
            //jika kosong
            if(setor==""){
                JOptionPane.showMessageDialog(null,"Penarikan Gagal. \n Isi jumlah penarikan anda" );
                tbpilih.setText("");
            }
            //jika kurang dari 50.000
            else if(setor1<50000){
                JOptionPane.showMessageDialog(null,"Minimal penarikan adalah Rp50.000");
                tbpilih.setText("");
            }
            //jika berhasil
            else{
                tab1 = tab-setor1;
                JOptionPane.showMessageDialog(null,"Penarikan berhasil. \n Saldo anda adalah Rp."+tab1 );}
            tbpilih.setText("");
            break;

            //kode petunjuk
            case 4:
            JOptionPane.showMessageDialog(null,"Cara Penggunaan Aplikasi\n"
                + "[1] Masukkan PIN dengan benar\n"
                + "[2] Bertransaksilah dengan benar sesuai pilihan\n"
                + "[3] Gunakan Uang sesuai kebutuhan dan rajinlah menabung\n "
                ,"INFO",1);
            tbpilih.setText("");
            break;

            //kode close
            case 5:
            JOptionPane.showMessageDialog(null,"Terimakasih telah melakukan transaksi.\n Semoga hari anda menyenangkan" );
            this.dispose();
            break;

            //jika tidak memenuhi 1-5
            default:
            JOptionPane.showMessageDialog(null,"Pilihan anda diluar Opsi. Silakan periksa kembali" );
            break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pilih().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tbpilih;
    // End of variables declaration//GEN-END:variables
}
